name: profile_app
description: "This is My Profile"

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.4
  figma_squircle: ^0.5.3
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  #this package is for App Icon
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.4
  go_router: ^13.2.2
  device_preview: ^1.1.0
  # Adapting Screen
  flutter_screenutil: ^5.9.3
  web: 0.5.1
  # Segmented Button
  segmented_button_slide: ^2.0.0
  # Photo Viewer
  photo_view: ^0.15.0
  # for SVG Files
  flutter_svg: ^2.0.10+1
  # GetX
  get: ^4.6.6
  # Equatable
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.12
  build_web_compilers: ^4.0.4
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/lottie/
      - assets/icons/
      - assets/fonts/
      - assets/svg/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 700

#App Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/user.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/user.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/user.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/user.png"


