name: profile_app
description: "This is My Profile"

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  equatable: ^2.0.5
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  go_router: ^13.2.2
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  photo_view: ^0.15.0
  pod_player: ^0.2.2
  segmented_button_slide: ^2.0.0
  url_launcher: ^6.2.4
  web: 0.5.1
  youtube_player_iframe: ^5.1.3

dev_dependencies:
  build_runner: ^2.4.12
  build_web_compilers: ^4.0.4

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/fonts/
    - assets/svg/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 700

#App Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/user.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/user.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/user.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/user.png"
